version: '3.8'

services:
  app:
    container_name: icitApp
    build: ./
    depends_on:
      - db
    volumes:
      - .container_images:/src/images
    ports:
      - '8000:8000'
    restart: always
    env_file:
      - .env
  db:
    container_name: scrapedimg
    image: postgres
    environment:
      - POSTGRES_DB=icitdb
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PSSWORD}
    ports:
      - '5432:5432'
    volumes:
      - .postgres:/var/lib/postgres/data
    restart: always